# Generated by Django 3.2.14 on 2022-07-11 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_auto_20220708_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='tag',
        ),
        migrations.AddField(
            model_name='photo',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='albums.tag', verbose_name='Тег'),
        ),
    ]
